<a href="https://colab.research.google.com/github/RomanKunal/Machine-Learning/blob/main/TrainAndTest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [2]:
data=pd.read_csv("/content/diabetes.csv")
data.head()

   Pregnancies  Glucose  BloodPressure  SkinThickness  ...   BMI  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72             35  ...  33.6                     0.627   50        1
1            1       85             66             29  ...  26.6                     0.351   31        0
2            8      183             64              0  ...  23.3                     0.672   32        1
3            1       89             66             23  ...  28.1                     0.167   21        0
4            0      137             40             35  ...  43.1                     2.288   33        1

[5 rows x 9 columns]

In [3]:
data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [4]:
X=data.drop(columns="Outcome",axis=1)
Y=data["Outcome"]

In [5]:
print(X)

     Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0              6      148             72  ...  33.6                     0.627   50
1              1       85             66  ...  26.6                     0.351   31
2              8      183             64  ...  23.3                     0.672   32
3              1       89             66  ...  28.1                     0.167   21
4              0      137             40  ...  43.1                     2.288   33
..           ...      ...            ...  ...   ...                       ...  ...
763           10      101             76  ...  32.9                     0.171   63
764            2      122             70  ...  36.8                     0.340   27
765            5      121             72  ...  26.2                     0.245   30
766            1      126             60  ...  30.1                     0.349   47
767            1       93             70  ...  30.4                     0.315   23

[768 rows x 8 columns]

In [6]:
print(Y)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [7]:
print(Y.std())

0.4769513772427971

In [8]:
print(X.std())

Pregnancies                   3.369578
Glucose                      31.972618
BloodPressure                19.355807
SkinThickness                15.952218
Insulin                     115.244002
BMI                           7.884160
DiabetesPedigreeFunction      0.331329
Age                          11.760232
dtype: float64

In [10]:
scaler=StandardScaler()
scaler.fit(X)
standardized_data=scaler.transform(X)

In [11]:
print(standardized_data.std())

1.0

In [13]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

In [15]:
print(X.shape,X_train.shape,X_test.shape)

(768, 8) (614, 8) (154, 8)

# HANDLING IMBALANCED DATASET
1. a dataset with an unequal distribution

In [16]:
cc=pd.read_csv("/content/credit_data.csv")
cc.head()

   Time        V1        V2        V3        V4  ...       V26       V27       V28  Amount  Class
0     0 -1.359807 -0.072781  2.536347  1.378155  ... -0.189115  0.133558 -0.021053  149.62    0.0
1     0  1.191857  0.266151  0.166480  0.448154  ...  0.125895 -0.008983  0.014724    2.69    0.0
2     1 -1.358354 -1.340163  1.773209  0.379780  ... -0.139097 -0.055353 -0.059752  378.66    0.0
3     1 -0.966272 -0.185226  1.792993 -0.863291  ... -0.221929  0.062723  0.061458  123.50    0.0
4     2 -1.158233  0.877737  1.548718  0.403034  ...  0.502292  0.219422  0.215153   69.99    0.0

[5 rows x 31 columns]

In [17]:
cc.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [18]:
cc["Class"].value_counts()

Class
0.0    51440
1.0      150
Name: count, dtype: int64

In [19]:
# seperate the fraud and legit trans as this is highly imbalanced dataset
legit=cc[cc.Class==0]
fraud=cc[cc.Class==1]

In [20]:
print(legit.shape)
print(fraud.shape)

(51440, 31)
(150, 31)

In [21]:
# BUILD A SAMPLE DATASET CONTAINING SIMILAR TRANS OD LEGIT AND FRAUD
legit_sample=legit.sample(n=492)
print(legit_sample.shape)

(492, 31)

In [22]:
# concat
new_dataset=pd.concat([legit_sample,fraud],axis=0)

In [23]:
new_dataset.head()

        Time         V1        V2        V3        V4  ...       V26       V27       V28  Amount  Class
36217  38440   1.236245 -0.138631  0.557991 -0.100567  ...  0.937310 -0.060007  0.004376    3.76    0.0
5795    6218  -0.118651 -0.113796  2.143746 -0.702922  ... -0.084274  0.165921  0.146390   21.00    0.0
30901  36132 -21.353056 -8.553351 -9.758950  6.121512  ... -0.050890  4.606591 -8.295258    1.00    0.0
39423  39831  -0.702846  0.451283 -0.028331 -2.290591  ... -0.486005 -0.047742  0.083333  136.67    0.0
8817   12039  -0.838089  0.886178  3.090743  2.088023  ... -0.030200  0.050492  0.060225    8.74    0.0

[5 rows x 31 columns]

In [24]:
new_dataset["Class"].value_counts()

Class
0.0    492
1.0    150
Name: count, dtype: int64